### ISSUE TITLE
The `add-path` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by youssef-tharwat** [winify-ag/setup-phraseapp#11]
I started receiving this warning message: 

The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by unrevised6419** [comment]
Published a new version with updated `@actions/core` this should be fixed
