### ISSUE TITLE
NodeJS v12 is deprecated

### ISSUE THREAD

**Issue by ghost** [winify-ag/setup-phraseapp#21]
When using this action GitHub warns that NodeJS v12 is deprecated:

`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: winify-ag/setup-phraseapp`

**Comment by skeeping** [comment]
I have created a pull request here https://github.com/winify-ag/setup-phraseapp/pull/22 if anyone with write access can test and approve it that would be great
