### ISSUE TITLE
V2: Error: Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by araujoigor** [winify-ag/setup-phraseapp#6]
Currently, the versioned `node_modules` (tag `releases/v2`) does not contain the `@actions` folder and thus it is leading to the action to not find the `core` module. Also, it seems that all dev deps are included (which we don't need).

I created #7 to fix this but since I didn't use the correct base branch for branching out, I could not remove the dev deps :(. Since I am in a hurry I left it like this.

**Comment by araujoigor** [comment]
Hey @iamandrewluca, any chance you can have a look on this?

**Comment by unrevised6419** [comment]
@araujoigor I'll take a look in weekend. Thanks for PR

**Comment by unrevised6419** [comment]
Fixed in 928c67422ae8b42912bfc312fee7674e1adeb448
